services:
  - type: web
    name: skyguard-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    region: oregon
    plan: free
